name: CI Symfony

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Lint PHP
        run: |
          find ./src -type f -name "*.php" -print0 | xargs -0 -n1 -P4 php -l

      - name: Lint YAML
        if: hashFiles('**/*.yaml','**/*.yml') != ''
        run: php bin/console lint:yaml config --parse-tags

      - name: Lint Twig
        if: hashFiles('templates/**/*.twig') != ''
        run: php bin/console lint:twig templates
